### ISSUE TITLE
[Question] Adding one crate

### ISSUE THREAD

**Issue by TornaxO7** [soywod/rfc2047-decoder#10]
Hi! I've a little suggestion here, do you agree if we add the [encoding_rs](https://crates.io/crates/encoding_rs) crate to handle the `encoding` token in the encoded word?

**Comment by soywod** [comment]
I do not think it is necessary, from their doc:

> Decoding Email

> For decoding character encodings that occur in email, use the charset crate instead of using this one directly. (It wraps this crate and adds UTF-7 decoding.)
 
We are already using the charset crate ;)
