### ISSUE TITLE
Errors discarded because of `flat_map`

### ISSUE THREAD

**Issue by soywod** [soywod/rfc2047-decoder#20]
https://github.com/soywod/rfc2047-decoder/blob/37af83b525ac7ff7269c94e64a795545bfa32ef9/src/evaluator.rs#L73-L87

The `flat_map` gets rid of all errors. If I have an error while decoding a string, I expect the `decode` function to return sth like `Err(DecodeBase64Error(InvalidByte(126, 61)))` instead of `Ok("")`.

**Comment by TornaxO7** [comment]
Are you sure that it gets rid of errors? Because I can't find anything in its [docs](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.flat_map) which says that it takes the errors.

**Comment by TornaxO7** [comment]
Fix by https://github.com/soywod/rfc2047-decoder/pull/21
