### ISSUE TITLE
Merging dev and bumping new version?

### ISSUE THREAD

**Issue by TornaxO7** [soywod/rfc2047-decoder#22]
@soywod one month has passed now and no new issues occured nor any features appeared. Should we merge the develop branch with the master and bump the version of this crate?

**Comment by TornaxO7** [comment]
If you want, I can do that as well. I've never done that before yet, but it's never too late for the first time :D

**Comment by soywod** [comment]
I (finally) created a matrix room for Himalaya, feel free to join at https://matrix.to/#/#himalaya.email.client:matrix.org :tada: 

> If you want, I can do that as well. I've never done that before yet, but it's never too late for the first time :D

I propose you to contact me directly at https://matrix.to/#/@soywod:matrix.org so I can explain you the procedure :slightly_smiling_face:

**Comment by soywod** [comment]
New version available: https://github.com/soywod/rfc2047-decoder/pull/23.

**Comment by TornaxO7** [comment]
I'm sorry for the (very) late reply! I was trying to get matrix working, but I can't connect with it somehow (or I'm doing something wrong) so I gave up for the time being but then I completely forgot it.

Now I'm still trying to get matrix working somehow but I'm still stuck with it. Do you have any tutroial recommondations?

**Comment by soywod** [comment]
> Now I'm still trying to get matrix working somehow but I'm still stuck
> with it. Do you have any tutroial recommondations?

Which client do you try to use? The easiest is to install element:
https://element.io/

**Comment by TornaxO7** [comment]
I'm trying to setup [fractal](https://matrix.org/docs/projects/client/fractal) but I'm failing with its question which provide I'm using. I'm always copy+pasting https://riot.im/app/#/home but it seems like that it isn't that what it means, right?

**Comment by soywod** [comment]
> I'm trying to setup fractal but I'm failing with its question which
> provide I'm using.

Not sure what they call provider, maybe ask the question directly on
their repo?
