### ISSUE TITLE
Bug: Lexer accepts too long encoded words.

### ISSUE THREAD

**Issue by TornaxO7** [soywod/rfc2047-decoder#29]
Currently `skip_encoded_word_length = false` doesn't work, it accepts too long encoded words.

**Comment by TornaxO7** [comment]
Ok... I'm stupid... the decoder will decode it as clear text, which is expected... *bonk*.

**Comment by TornaxO7** [comment]
Hm... but wait, this might be good to discuss as this might not be the expected behaviour :thinking:

**Comment by TornaxO7** [comment]
# How it is at the moment
Assuming we have the following encoded string:
```
=?UTF-8?B?VGhpcyBzdHJpbmcgaXMgbW9yZSB0aGFuIDc1IGNoYXJhY3RlcnMgbG9uZyB3aGljaCBpcyBpbnZhbGlkIGFjY29yZGluZyB0byBSRkMgNDAyNy4=?=
```
which is `This string is more than 75 characters long which is invalid according to RFC 4027.` decoded, if we ignore the length,
the decoder at the moment, reads that as a clear-text string. Is that fine or should it as an error?

**Comment by TornaxO7** [comment]
@soywod

**Comment by soywod** [comment]
I would say if `skip_encoded_word_length = true` then it should decode
strings longer than 75 chars. If `skip_encoded_word_length = false` then
it should return an error when strings are longer than 75 chars. Does it
make sense to you?

**Comment by TornaxO7** [comment]
yes, that would make sense to me, but that would lead to a breaking change: There won't be a cleartext option anymore.
Wolud you agree on this?

**Comment by soywod** [comment]
> yes, that would make sense to me, but that would lead to a breaking
> change: There won't be a cleartext option anymore.  Wolud you agree on
> this?

I forgot about this option. So I would say if the skip length is true
and this option is true, then it should not return an error.

**Comment by TornaxO7** [comment]
To be honest, I'd prefer to do the breaking change and remove the cleartext option, because as an API-User because there's no real benefit of having the `ClearText` enumerate-option since you can simpley do
```rust
let text = rfc2047::decode(&text).unwrap_or(text);
```
and you have the cleartext as well.

**Comment by soywod** [comment]
I totally agree with you, let's go for it!

**Comment by TornaxO7** [comment]
Would you also agree to let the `decode` function try to decode only *one* encoded word?
As an API-User this should give me the ability to work with the string in more detail, for example if I only want to decode the first encoded word and not the whole string.

**Comment by soywod** [comment]
> Would you also agree to let the `decode` function try to decode only
> *one* encoded word?

You mean by introducing a new option for this purpose? If so then yes!

**Comment by TornaxO7** [comment]
Ok, now I'm bit unsure what to do.
Assuming we've got the following encoded word:
```
=?ISO-8859-1?Q?aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa?=```

I'm seeing *three* possible ways with it:

1. Throw an error, since it doesn't suit the RFC. (what I'd expect to happen)
2. Parse that as a clear-text token. (what we do currently)
3. Decode the string neverthless. (what we do currently, if the skip-option is set)

What do you think about this one?

**Comment by soywod** [comment]
To be as generic as possible we could accept all those cases using an
enum option, sth like:

```rust
pub enum DecodeTooBigWordStrategy {
    DecodeAnyway,
    KeepEncoded,
    Abort,
}
```

**Comment by TornaxO7** [comment]
this sounds reasonable.

**Comment by TornaxO7** [comment]
> To be honest, I'd prefer to do the breaking change and remove the cleartext option, because as an API-User because there's no real benefit of having the `ClearText` enumerate-option since you can simpley do
> 
> ```rust
> let text = rfc2047::decode(&text).unwrap_or(text);
> ```
> 
> and you have the cleartext as well.

ok, so there's a problem with this:

Assuming we would do it like that, then we wouldn't be able to parse text, which mixes encoded words with clear text like:
```
=?ISO-8859-1?Q?a?= b
```
since we don't allow clear text anymore.... oh man... this is pretty annoying :(

**Comment by soywod** [comment]
Why did we want to remove the clear text option?

**Comment by TornaxO7** [comment]
I'm sorry for the late answer!

> Why did we want to remove the clear text option?

At the beginning because it seems to be unnecessary. However, it appears to be not unnecessary now.

**Comment by soywod** [comment]
> At the beginning because it seems to be unnecessary. However, it
> appears to be not unnecessary now.

So let's put it back?

**Comment by TornaxO7** [comment]
yeah I didn't remove it.

**Comment by TornaxO7** [comment]
Closed due to https://github.com/soywod/rfc2047-decoder/pull/31
