### ISSUE TITLE
Pipeline didn't publish new version

### ISSUE THREAD

**Issue by TornaxO7** [soywod/rfc2047-decoder#33]
Hm... did something went wrong after merging https://github.com/soywod/rfc2047-decoder/pull/32?
I can't see a new released package.

**Comment by TornaxO7** [comment]
Hm... looks like that my tag isn't listed (`v1.0.0`)? https://github.com/soywod/rfc2047-decoder/tags

**Comment by TornaxO7** [comment]
oh, I needed to push the tags as well with `git push upstream --tags`...

**Comment by TornaxO7** [comment]
yay, it worked!

**Comment by soywod** [comment]
> oh, I needed to push the tags as well with `git push upstream
> --tags`...

Yes, tags are not pushed by default.
