### ISSUE TITLE
[Question] Adding thiserror?

### ISSUE THREAD

**Issue by TornaxO7** [soywod/rfc2047-decoder#5]
Hi! I've got a little question: Could we add [`thiserror`](https://crates.io/crates/thiserror) to this lib because I think that this could reduce some LOC without losing maintainabilitiy.

**Comment by soywod** [comment]
Yep, totally! I initiated this lib a long time ago and I did not know about `thiserror`.

**Comment by TornaxO7** [comment]
Can I do that?

**Comment by soywod** [comment]
Of course :ok_hand:

**Comment by TornaxO7** [comment]
Hm... I'm unsure what this should return for the error-value:

```rust
pub fn decode(encoded_str: &[u8]) -> Result<String, ?> {
    let tokens = lexer::run(&encoded_str)?;
    let ats = parser::run(&tokens)?;
    let decoded_str = evaluator::run(&ats)?;

    Ok(decoded_str)
}
```

any suggestions?
