### ISSUE TITLE
[Question] Using chumsky to parse the tokens

### ISSUE THREAD

**Issue by TornaxO7** [soywod/rfc2047-decoder#7]
Hi! I have a suggestion here:

I'd like to refactor your [`run`](https://github.com/soywod/rfc2047-decoder/blob/master/src/lexer.rs#L47) function in the `lexer.rs` to a ~~[`context-free grammar`](https://en.wikipedia.org/wiki/Context-free_grammar) "construction". Did you try to implement a [finite-state machine](https://en.wikipedia.org/wiki/Finite-state_machine)? I think a context-free grammar should reduce the code-complexity (or even a finite-state machine, but I prefer a context-free grammar :))~~

function which uses [`chumsky crate`](https://crates.io/crates/chumsky). It looks very promising in my opinion which should help us to make it better to maintain and especially getting better error messages!

**Comment by TornaxO7** [comment]
@soywod

**Comment by soywod** [comment]
Looks great indeed, I knew https://github.com/rust-num/num but it looks a bit less active then chumsky. Give it a try!

**Comment by TornaxO7** [comment]
Done in #11
