### ISSUE TITLE
[Question] Clear Text

### ISSUE THREAD

**Issue by TornaxO7** [soywod/rfc2047-decoder#9]
[Here](https://github.com/soywod/rfc2047-decoder/blob/master/src/parser.rs#L60) you added a "clear text" match. If I'm trying to lookup the word "Clear" in the [RFC](https://datatracker.ietf.org/doc/html/rfc2047#section-3) then I'm getting no results. May I ask you added this "ClearText" enum entry?

**Comment by soywod** [comment]
Clear just means unencoded bytes in this context.
